import type {Metadata} from "next";
import "./globals.css";
import {QueryProvider} from "@/app/provider/query-provider";
import {GlobalPersianDigits} from "@/app/provider/global-persian-digits";

export const metadata: Metadata = {
    title: "Neo Bank",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa">
        <body className="antialiased">
        <QueryProvider>
            <GlobalPersianDigits>
                <div className="app-container min-h-screen">
                    {children}
                </div>
            </GlobalPersianDigits>
        </QueryProvider>
        </body>
        </html>
    );
}
